version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test # Created on image startup
  nats:
    image: "nats-streaming:0.17.0"
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "-p 4222 -m 8222 -hbi 5s -hbf 2 -SD -cid test"
