apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: tajpouria/stub-auth
      context: ./packages/auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: tajpouria/stub-client
      context: ./packages/client
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.ts"
            dest: .
          - src: "**/*.vue"
            dest: .
          - src: "assets/**/*.*"
            dest: .
          - src: "static/**/*.*"
            dest: .
          - src: "locales/*.json"
            dest: .
