apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: tajpouria/stub-auth-service
      context: packages/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "src/**/*.html"
            dest: .
    - image: tajpouria/stub-client-service
      context: packages/client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.ts"
            dest: .
          - src: "**/*.vue"
            dest: .
          - src: "assets/**/*.*"
            dest: .
          - src: "static/**/*.*"
            dest: .
          - src: "locales/*.json"
            dest: .
