apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      name: auth-pod
  template:
    metadata:
      name: auth
      labels:
        name: auth-pod
        tier: back-end
    spec:
      containers:
        - name: stub-auth
          image: tajpouria/stub-auth
          env:
            - name: NAME
              value: "Auth"
            - name: HOST
              value: "https://stub.dev"
            - name: VERSION
              value: "0.0.1"
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "4000"
            - name: DB_URL
              value: "mongodb://auth-mongo-clusterip/auth"
            - name: SESSION_NAME
              value: session
            - name: REDIS_URL
              value: "auth-redis-clusterip:6379"
            - name: REDIS_EXPIRY_SECONDS
              value: "10800" # 3 Hours
            - name: MAILER
              valueFrom:
                secretKeyRef:
                  name: stub-secret
                  key: MAILER
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: stub-secret
                  key: JWT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: stub-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: stub-secret
                  key: GOOGLE_CLIENT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip
spec:
  selector:
    name: auth-pod
  ports:
    - name: auth
      protocol: TCP
      targetPort: 4000
      port: 4000
