apiVersion: apps/v1
kind: Deployment
metadata:
  name: charge 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: charge-pod
  template:
    metadata:
      name: charge 
      labels:
        name: charge-pod
        tier: back-end
    spec:
      containers:
        - name: stub-charge-service
          image: tajpouria/stub-charge-service
          env:
            - name: NAME
              value: "Charge"
            - name: NODE_ENV
              value: "development"
            - name: HOST
              value: "https://stub.dev"
            - name: PORT
              value: "7000"
            - name: SESSION_NAME
              value: "session"
            - name: ORM_CONFIG
              value: '{"type": "mysql","host": "charge-mysql-clusterip","port": 3306,"username": "root","password": "root","database": "main"}'
            - name: NATS_URL
              value: "http://stub-nats-clusterip:4222"
            - name: NATS_CLUSTER_ID
              value: "stub"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: stub-secret
                  key: JWT_SECRET
            - name: STRIPE_SECRET_KEY 
              valueFrom:
                secretKeyRef:
                  name: stub-secret
                  key: STRIPE_SECRET_KEY 

---
apiVersion: v1
kind: Service
metadata:
  name: charge-clusterip
spec:
  selector:
    name: charge-pod
  ports:
    - name:charge 
      protocol: TCP
      targetPort: 6000
      port: 6000
