apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      name: order-pod
  template:
    metadata:
      name: order
      labels:
        name: order-pod
        tier: back-end
    spec:
      containers:
        - name: stub-order-service
          image: tajpouria/stub-order-service
          env:
            - name: NAME
              value: "Order"
            - name: NODE_ENV
              value: "development"
            - name: HOST
              value: "https://stub.dev"
            - name: PORT
              value: "6000"
            - name: SESSION_NAME
              value: "session"
            - name: ORM_CONFIG
              value: '{"type": "mysql","host": "order-mysql-clusterip","port": 3306,"username": "root","password": "root","database": "main"}'
            - name: NATS_URL
              value: "http://stub-nats-clusterip:4222"
            - name: NATS_CLUSTER_ID
              value: "stub"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: stub-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: order-clusterip
spec:
  selector:
    name: order-pod
  ports:
    - name: order
      protocol: TCP
      targetPort: 6000
      port: 6000
