apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ticket-pod
  template:
    metadata:
      name: ticket
      labels:
        name: ticket-pod
        tier: back-end
    spec:
      containers:
        - name: stub-ticket-service
          image: tajpouria/stub-ticket-service
          env:
            - name: NAME
              value: "Ticket"
            - name: NODE_ENV
              value: "development"
            - name: HOST
              value: "https://stub.dev"
            - name: PORT
              value: "5000"
            - name: SESSION_NAME
              value: "session"
            - name: ORM_CONFIG
              value: '{"type": "mysql","host": "ticket-mysql-clusterip","port": 3306,"username": "root","password": "root","database": "main"}'
            - name: URL_PATTERN
              value: "/((http|https)://?)[^s()<>]+(?:([wd]+)|([^[:punct:]s]|/?))/"
            - name: NATS_URL
              value: "http://stub-nats-clusterip:4222"
            - name: NATS_CLUSTER_ID
              value: "stub"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: stub-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-clusterip
spec:
  selector:
    name: ticket-pod
  ports:
    - name: ticket
      protocol: TCP
      targetPort: 5000
      port: 5000
