# Provide
# http://github.com/tajpouria/stub/tree/master/packages/auth
# http://github.com/tajpouria/stub/tree/master/packages/ticket
# http://github.com/tajpouria/stub/tree/master/packages/order
# development requirements
version: "3"
services:
  nats:
    image: nats-streaming:0.17.0
    command: "-p 4222 -m 8222 -hbi 5s -hbt 5s -hbf 2 -SD -cid stub"
    ports:
      - "4222:4222"
      - "8222:8222"
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
